/* 회원 */
CREATE TABLE MEMBERS (
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	PWD VARCHAR2(20) NOT NULL, /* 비밀번호 */
	NICKNAME VARCHAR2(20) NOT NULL, /* 닉네임 */
	AGE NUMBER, /* 나이 */
	GENDER VARCHAR2(2), /* 성별 */
	EMAIL VARCHAR2(20), /* 이메일 */
	PARTNER VARCHAR2(20), /* 파트너 */
	RUBY NUMBER /* 루비(포인트) */
);

COMMENT ON TABLE MEMBERS IS '회원';

COMMENT ON COLUMN MEMBERS.ID IS '아이디';

COMMENT ON COLUMN MEMBERS.PWD IS '비밀번호';

COMMENT ON COLUMN MEMBERS.NICKNAME IS '닉네임';

COMMENT ON COLUMN MEMBERS.AGE IS '나이';

COMMENT ON COLUMN MEMBERS.GENDER IS '성별';

COMMENT ON COLUMN MEMBERS.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBERS.PARTNER IS '파트너';

COMMENT ON COLUMN MEMBERS.RUBY IS '루비(포인트)';

CREATE UNIQUE INDEX PK_MEMBERS
	ON MEMBERS (
		ID ASC
	);

ALTER TABLE MEMBERS
	ADD
		CONSTRAINT PK_MEMBERS
		PRIMARY KEY (
			ID
		);

/* 콘텐츠 */
CREATE TABLE CONTENT (
	CONTENTNUM NUMBER NOT NULL, /* 콘텐츠번호 */
	EXPECTEDHOUR NUMBER, /* 예상 소요시간 */
	CONTENT VARCHAR2(1000) NOT NULL, /* 글내용 */
	GOOD NUMBER, /* 좋아요 */
	TITLE VARCHAR2(100) NOT NULL, /* 글제목 */
	THEMENUM NUMBER NOT NULL, /* 테마번호 */
	REGIONNUM NUMBER NOT NULL /* 지역번호 */
);

COMMENT ON TABLE CONTENT IS '콘텐츠';

COMMENT ON COLUMN CONTENT.CONTENTNUM IS '콘텐츠번호';

COMMENT ON COLUMN CONTENT.EXPECTEDHOUR IS '예상 소요시간';

COMMENT ON COLUMN CONTENT.CONTENT IS '글내용';

COMMENT ON COLUMN CONTENT.GOOD IS '좋아요';

COMMENT ON COLUMN CONTENT.TITLE IS '글제목';

COMMENT ON COLUMN CONTENT.THEMENUM IS '테마번호';

COMMENT ON COLUMN CONTENT.REGIONNUM IS '지역번호';

CREATE UNIQUE INDEX PK_CONTENT
	ON CONTENT (
		CONTENTNUM ASC
	);

ALTER TABLE CONTENT
	ADD
		CONSTRAINT PK_CONTENT
		PRIMARY KEY (
			CONTENTNUM
		);

/* 테마 */
CREATE TABLE THEME (
	THEMENUM NUMBER NOT NULL, /* 테마번호 */
	THEMENAME VARCHAR2(20) NOT NULL, /* 테마이름 */
	THEMEICON BLOB NOT NULL /* 테마아이콘 */
);

COMMENT ON TABLE THEME IS '테마';

COMMENT ON COLUMN THEME.THEMENUM IS '테마번호';

COMMENT ON COLUMN THEME.THEMENAME IS '테마이름';

COMMENT ON COLUMN THEME.THEMEICON IS '테마아이콘';

CREATE UNIQUE INDEX PK_THEME
	ON THEME (
		THEMENUM ASC
	);

ALTER TABLE THEME
	ADD
		CONSTRAINT PK_THEME
		PRIMARY KEY (
			THEMENUM
		);

/* 지역 */
CREATE TABLE REGION (
	REGIONNUM NUMBER NOT NULL, /* 지역번호 */
	REGIONNAME VARCHAR2(20) NOT NULL, /* 지역이름 */
	REGIONICON BLOB NOT NULL /* 지역아이콘 */
);

COMMENT ON TABLE REGION IS '지역';

COMMENT ON COLUMN REGION.REGIONNUM IS '지역번호';

COMMENT ON COLUMN REGION.REGIONNAME IS '지역이름';

COMMENT ON COLUMN REGION.REGIONICON IS '지역아이콘';

CREATE UNIQUE INDEX PK_REGION
	ON REGION (
		REGIONNUM ASC
	);

ALTER TABLE REGION
	ADD
		CONSTRAINT PK_REGION
		PRIMARY KEY (
			REGIONNUM
		);

/* 찜목록 */
CREATE TABLE POINT (
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	CONTENTNUM NUMBER NOT NULL /* 콘텐츠번호 */
);

COMMENT ON TABLE POINT IS '찜목록';

COMMENT ON COLUMN POINT.ID IS '아이디';

COMMENT ON COLUMN POINT.CONTENTNUM IS '콘텐츠번호';

CREATE UNIQUE INDEX PK_POINT
	ON POINT (
		ID ASC,
		CONTENTNUM ASC
	);

ALTER TABLE POINT
	ADD
		CONSTRAINT PK_POINT
		PRIMARY KEY (
			ID,
			CONTENTNUM
		);

/* 일정표 */
CREATE TABLE SCHEDULES (
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	DAY DATE NOT NULL /* 날짜 */
);

COMMENT ON TABLE SCHEDULES IS '일정표';

COMMENT ON COLUMN SCHEDULES.ID IS '아이디';

COMMENT ON COLUMN SCHEDULES.DAY IS '날짜';

CREATE UNIQUE INDEX PK_SCHEDULES
	ON SCHEDULES (
		ID ASC,
		DAY ASC
	);

ALTER TABLE SCHEDULES
	ADD
		CONSTRAINT PK_SCHEDULES
		PRIMARY KEY (
			ID,
			DAY
		);

/* 시간표 */
CREATE TABLE TIMESHEET (
	HOUR NUMBER NOT NULL, /* 시각 */
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	DAY DATE NOT NULL, /* 날짜 */
	CONTENTNUM NUMBER NOT NULL /* 콘텐츠번호 */
);

COMMENT ON TABLE TIMESHEET IS '시간표';

COMMENT ON COLUMN TIMESHEET.HOUR IS '시각';

COMMENT ON COLUMN TIMESHEET.ID IS '아이디';

COMMENT ON COLUMN TIMESHEET.DAY IS '날짜';

COMMENT ON COLUMN TIMESHEET.CONTENTNUM IS '콘텐츠번호';

CREATE UNIQUE INDEX PK_TIMESHEET
	ON TIMESHEET (
		HOUR ASC,
		ID ASC,
		DAY ASC
	);

ALTER TABLE TIMESHEET
	ADD
		CONSTRAINT PK_TIMESHEET
		PRIMARY KEY (
			HOUR,
			ID,
			DAY
		);

/* 리뷰 */
CREATE TABLE REVIEW (
	CONTENTNUM NUMBER NOT NULL, /* 콘텐츠번호 */
	ID VARCHAR2(20) NOT NULL, /* 아이디 */
	REVIEWCONTENT VARCHAR2(100) NOT NULL /* 글내용 */
);

COMMENT ON TABLE REVIEW IS '리뷰';

COMMENT ON COLUMN REVIEW.CONTENTNUM IS '콘텐츠번호';

COMMENT ON COLUMN REVIEW.ID IS '아이디';

COMMENT ON COLUMN REVIEW.REVIEWCONTENT IS '글내용';

CREATE UNIQUE INDEX PK_REVIEW
	ON REVIEW (
		CONTENTNUM ASC,
		ID ASC
	);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT PK_REVIEW
		PRIMARY KEY (
			CONTENTNUM,
			ID
		);

/* 커플신청 */
CREATE TABLE PARTNER (
	ID VARCHAR2(20) NOT NULL, /* 신청한 아이디 */
	CANDIDATE VARCHAR2(20) NOT NULL /* 신청받은 아이디 */
);

COMMENT ON TABLE PARTNER IS '커플신청';

COMMENT ON COLUMN PARTNER.ID IS '신청한 아이디';

COMMENT ON COLUMN PARTNER.CANDIDATE IS '신청받은 아이디';

CREATE UNIQUE INDEX PK_PARTNER
	ON PARTNER (
		ID ASC,
		CANDIDATE ASC
	);

ALTER TABLE PARTNER
	ADD
		CONSTRAINT PK_PARTNER
		PRIMARY KEY (
			ID,
			CANDIDATE
		);

/* 콘텐츠이미지 */
CREATE TABLE IMAGE (
	IMAGE BLOB NOT NULL, /* 콘텐츠이미지 */
	CONTENTNUM NUMBER NOT NULL, /* 콘텐츠번호 */
	TOPIMAGE NUMBER /* 대표이미지 */
);

COMMENT ON TABLE IMAGE IS '콘텐츠이미지';

COMMENT ON COLUMN IMAGE.IMAGE IS '콘텐츠이미지';

COMMENT ON COLUMN IMAGE.CONTENTNUM IS '콘텐츠번호';

COMMENT ON COLUMN IMAGE.TOPIMAGE IS '대표이미지';

ALTER TABLE MEMBERS
	ADD
		CONSTRAINT FK_MEMBERS_TO_MEMBERS
		FOREIGN KEY (
			PARTNER
		)
		REFERENCES MEMBERS (
			ID
		);

ALTER TABLE CONTENT
	ADD
		CONSTRAINT FK_THEME_TO_CONTENT
		FOREIGN KEY (
			THEMENUM
		)
		REFERENCES THEME (
			THEMENUM
		);

ALTER TABLE CONTENT
	ADD
		CONSTRAINT FK_REGION_TO_CONTENT
		FOREIGN KEY (
			REGIONNUM
		)
		REFERENCES REGION (
			REGIONNUM
		);

ALTER TABLE POINT
	ADD
		CONSTRAINT FK_MEMBERS_TO_POINT
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBERS (
			ID
		);

ALTER TABLE POINT
	ADD
		CONSTRAINT FK_CONTENT_TO_POINT
		FOREIGN KEY (
			CONTENTNUM
		)
		REFERENCES CONTENT (
			CONTENTNUM
		);

ALTER TABLE SCHEDULES
	ADD
		CONSTRAINT FK_MEMBERS_TO_SCHEDULES
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBERS (
			ID
		);

ALTER TABLE TIMESHEET
	ADD
		CONSTRAINT FK_CONTENT_TO_TIMESHEET
		FOREIGN KEY (
			CONTENTNUM
		)
		REFERENCES CONTENT (
			CONTENTNUM
		);

ALTER TABLE TIMESHEET
	ADD
		CONSTRAINT FK_SCHEDULES_TO_TIMESHEET
		FOREIGN KEY (
			ID,
			DAY
		)
		REFERENCES SCHEDULES (
			ID,
			DAY
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_MEMBERS_TO_REVIEW
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBERS (
			ID
		);

ALTER TABLE REVIEW
	ADD
		CONSTRAINT FK_CONTENT_TO_REVIEW
		FOREIGN KEY (
			CONTENTNUM
		)
		REFERENCES CONTENT (
			CONTENTNUM
		);

ALTER TABLE PARTNER
	ADD
		CONSTRAINT FK_MEMBERS_TO_PARTNER2
		FOREIGN KEY (
			ID
		)
		REFERENCES MEMBERS (
			ID
		);

ALTER TABLE PARTNER
	ADD
		CONSTRAINT FK_MEMBERS_TO_PARTNER
		FOREIGN KEY (
			CANDIDATE
		)
		REFERENCES MEMBERS (
			ID
		);

ALTER TABLE IMAGE
	ADD
		CONSTRAINT FK_CONTENT_TO_IMAGE
		FOREIGN KEY (
			CONTENTNUM
		)
		REFERENCES CONTENT (
			CONTENTNUM
		);