/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.7
 * Generated at: 2018-04-14 07:25:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/sts_bitcamp/STS-Study/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Ex01_Study/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1523676572924L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write(" \n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\n");
      out.write("\t<title>Insert title here</title>\n");
      out.write("\t<script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pagecontext.request.contextpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/ckeditor/ckeditor.js\"></script>\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-1.12.4.js\"></script>\n");
      out.write("  \t<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pagecontext.request.contextpath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/content.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write(" \n");
      out.write(" \n");
      out.write(" \n");
      out.write(" <!-- 파일 업로드 참조 http://www.happyjung.com/lecture/2069 -->\n");
      out.write(" \n");
      out.write("\t<SCRIPT type=\"text/javascript\">\n");
      out.write("\t\n");
      out.write("\tfunction previewImage(targetObj, View_area) {\n");
      out.write("\t\tvar preview = document.getElementById(View_area); //div id\n");
      out.write("\t\tvar ua = window.navigator.userAgent;\n");
      out.write("\t  //ie일때(IE8 이하에서만 작동)\n");
      out.write("\t\tif (ua.indexOf(\"MSIE\") > -1) {\n");
      out.write("\t\t\ttargetObj.select();\n");
      out.write("\t\t\ttry {\n");
      out.write("\t\t\t\tvar src = document.selection.createRange().text; // get file full path(IE9, IE10에서 사용 불가)\n");
      out.write("\t\t\t\tvar ie_preview_error = document.getElementById(\"ie_preview_error_\" + View_area);\n");
      out.write("\t\t\t\tif (ie_preview_error) {\n");
      out.write("\t\t\t\t\tpreview.removeChild(ie_preview_error); //error가 있으면 delete\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tvar img = document.getElementById(View_area); //이미지가 뿌려질 곳\n");
      out.write("\t\t\t\t//이미지 로딩, sizingMethod는 div에 맞춰서 사이즈를 자동조절 하는 역할\n");
      out.write("\t\t\t\timg.style.filter = \"progid:DXImageTransform.Microsoft.AlphaImageLoader(src='\"+src+\"', sizingMethod='scale')\";\n");
      out.write("\t\t\t} catch (e) {\n");
      out.write("\t\t\t\tif (!document.getElementById(\"ie_preview_error_\" + View_area)) {\n");
      out.write("\t\t\t\t\tvar info = document.createElement(\"<p>\");\n");
      out.write("\t\t\t\t\tinfo.id = \"ie_preview_error_\" + View_area;\n");
      out.write("\t\t\t\t\tinfo.innerHTML = e.name;\n");
      out.write("\t\t\t\t\tpreview.insertBefore(info, null);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t  //ie가 아닐때(크롬, 사파리, FF)\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tvar files = targetObj.files;\n");
      out.write("\t\t\tfor ( var i = 0; i < files.length; i++) {\n");
      out.write("\t\t\t\tvar file = files[i];\n");
      out.write("\t\t\t\tvar imageType = /image.*/; //이미지 파일일경우만.. 뿌려준다.\n");
      out.write("\t\t\t\tif (!file.type.match(imageType))\n");
      out.write("\t\t\t\t\tcontinue;\n");
      out.write("\t\t\t\tvar prevImg = document.getElementById(\"prev_\" + View_area); //이전에 미리보기가 있다면 삭제\n");
      out.write("\t\t\t\tif (prevImg) {\n");
      out.write("\t\t\t\t\tpreview.removeChild(prevImg);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tvar img = document.createElement(\"img\"); \n");
      out.write("\t\t\t\timg.id = \"prev_\" + View_area;\n");
      out.write("\t\t\t\timg.classList.add(\"obj\");\n");
      out.write("\t\t\t\timg.file = file;\n");
      out.write("\t\t\t\timg.style.width = '100px'; \n");
      out.write("\t\t\t\timg.style.height = '100px';\n");
      out.write("\t\t\t\tpreview.appendChild(img);\n");
      out.write("\t\t\t\tif (window.FileReader) { // FireFox, Chrome, Opera 확인.\n");
      out.write("\t\t\t\t\tvar reader = new FileReader();\n");
      out.write("\t\t\t\t\treader.onloadend = (function(aImg) {\n");
      out.write("\t\t\t\t\t\treturn function(e) {\n");
      out.write("\t\t\t\t\t\t\taImg.src = e.target.result;\n");
      out.write("\t\t\t\t\t\t};\n");
      out.write("\t\t\t\t\t})(img);\n");
      out.write("\t\t\t\t\treader.readAsDataURL(file);\n");
      out.write("\t\t\t\t} else { // safari is not supported FileReader\n");
      out.write("\t\t\t\t\t//alert('not supported FileReader');\n");
      out.write("\t\t\t\t\tif (!document.getElementById(\"sfr_preview_error_\"\n");
      out.write("\t\t\t\t\t\t\t+ View_area)) {\n");
      out.write("\t\t\t\t\t\tvar info = document.createElement(\"p\");\n");
      out.write("\t\t\t\t\t\tinfo.id = \"sfr_preview_error_\" + View_area;\n");
      out.write("\t\t\t\t\t\tinfo.innerHTML = \"not supported FileReader\";\n");
      out.write("\t\t\t\t\t\tpreview.insertBefore(info, null);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\tfunction check(){\n");
      out.write("\t\talert(\"check()\")\n");
      out.write("\t\n");
      out.write("\t\tdocument.db.submit();\n");
      out.write("\t\t\t\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("  $( function() {\n");
      out.write("    $.widget( \"custom.iconselectmenu\", $.ui.selectmenu, {\n");
      out.write("      _renderItem: function( ul, item ) {\n");
      out.write("        var li = $( \"<li>\" ),\n");
      out.write("          wrapper = $( \"<div>\", { text: item.label } );\n");
      out.write(" \n");
      out.write("        if ( item.disabled ) {\n");
      out.write("          li.addClass( \"ui-state-disabled\" );\n");
      out.write("        }\n");
      out.write(" \n");
      out.write("        $( \"<span>\", {\n");
      out.write("          style: item.element.attr( \"data-style\" ),\n");
      out.write("          \"class\": \"ui-icon \" + item.element.attr( \"data-class\" )\n");
      out.write("        })\n");
      out.write("          .appendTo( wrapper );\n");
      out.write(" \n");
      out.write("        return li.append( wrapper ).appendTo( ul );\n");
      out.write("      }\n");
      out.write("    });\n");
      out.write(" \n");
      out.write(" \n");
      out.write("    $( \"#theme\" )\n");
      out.write("      .iconselectmenu()\n");
      out.write("      .iconselectmenu( \"menuWidget\" )\n");
      out.write("        .addClass( \"ui-menu-icons customicons\" );\n");
      out.write("    \n");
      out.write("    $( \"#region\" )\n");
      out.write("    .iconselectmenu()\n");
      out.write("    .iconselectmenu( \"menuWidget\" )\n");
      out.write("      .addClass( \"ui-menu-icons customicons\" );\n");
      out.write(" \n");
      out.write("    \n");
      out.write("    \n");
      out.write("          \n");
      out.write("    \n");
      out.write("  } );\n");
      out.write("  </script>\n");
      out.write("  <style>\n");
      out.write("  \n");
      out.write("    h2 {\n");
      out.write("      margin: 30px 0 0 0;\n");
      out.write("    }\n");
      out.write(" \n");
      out.write("    /* select with custom icons */\n");
      out.write("    .ui-selectmenu-menu  .ui-menu-item-wrapper {\n");
      out.write("      padding: 0.5em 0 0.5em 3em;\n");
      out.write("    }\n");
      out.write("    .ui-selectmenu-menu .ui-menu-item .ui-icon {\n");
      out.write("      height: 24px;\n");
      out.write("      width: 24px;\n");
      out.write("      top: 0.1em;\n");
      out.write("    }\n");
      out.write("    /* 아이콘 이미지 파일 경로  */\n");
      out.write("    .ui-icon.video {\n");
      out.write("      background: url(\"images/test.JPG\") 0 0 no-repeat;\n");
      out.write("      \n");
      out.write("    }\n");
      out.write("    .ui-icon.podcast {\n");
      out.write("      background: url(\"images/test.JPG\") 0 0 no-repeat;\n");
      out.write("    }\n");
      out.write("    .ui-icon.rss {\n");
      out.write("      background: url(\"images/test.JPG\") 0 0 no-repeat;\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    .color{\n");
      out.write("    color: white;\n");
      out.write("    background-color: #FAB0BF;\n");
      out.write("    \n");
      out.write("    }\n");
      out.write("    /* 클릭시 outline 파란색 없애기  */\n");
      out.write("   .click{\n");
      out.write("   \tborder : 0;\n");
      out.write("   \toutline: 0;\n");
      out.write("   }\n");
      out.write(" .click:focus,.click:active {\n");
      out.write("   outline: none !important;\n");
      out.write("   box-shadow: none;\n");
      out.write("\t} \n");
      out.write("\t\n");
      out.write("\t*:focus{\n");
      out.write("\toutline: 0;\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("  </style>\n");
      out.write("\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body  style=\"background-color:#FFF1EA;\">\n");
      out.write("\t\t<!-- header -->\n");
      out.write("\t\n");
      out.write("\t\t<!-- writer -->\n");
      out.write("\t\t<div class= \"container\"  >\n");
      out.write("\t\t\t<form name = \"db\" action=\"content_testing.jsp\" method = \"POST\" enctype=\"multipart/form-data\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<table width=\"100%\" border=\"0\" align=\"center\">\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"left\" colspan=\"2\"> <h2>글 작성하기</h2></td>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" height= \"24px\" align=\"center\" ></td>\n");
      out.write("\t\t\t\t\t\t<td  style=\"visibility:hidden;\">empty</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" class=\"color\" > 제목</td>\n");
      out.write("\t\t\t\t\t\t<td width=\"40\" align=\"left\"><input type=\"text\" name= \"subject\" size=\"40\"></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" ></td>\n");
      out.write("\t\t\t\t\t\t<td  style=\"visibility:hidden;\">empty</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" class=\"color \"> 테마</td>\n");
      out.write("\t\t\t\t\t\t<td width=\"40%\" >\n");
      out.write("\t\t\t\t\t\t\t<select name=\"theme\" id=\"theme\">\n");
      out.write("\t\t\t\t\t\t\t<!-- 나중에 THEME 테이블에서 테마 이름, 테마 그림을 가져와야한다.  -->\n");
      out.write("\t\t      \t\t\t\t\t<option data-class=\"podcast\" >꽃놀이</option>\n");
      out.write("\t\t    \t\t\t  \t\t<option data-class=\"podcast\">야경</option>\n");
      out.write("\t\t     \t\t\t\t\t<option selected=\"selected\" data-class=\"podcast\">식당</option>\n");
      out.write("\t\t      \t\t\t\t\t<option data-class=\"podcast\">운동</option>\n");
      out.write("\t\t      \t\t\t\t\t<option data-class=\"podcast\">놀이동산</option>\n");
      out.write("\t   \t\t\t\t\t\t </select>\n");
      out.write("   \t\t\t\t\t\t </td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" ></td>\n");
      out.write("\t\t\t\t\t\t<td  style=\"visibility:hidden;\">empty</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" class=\"color \"> 지역</td>\n");
      out.write("\t\t\t\t\t\t<td width=\"40%\" >\n");
      out.write("\t\t\t\t\t\t\t<select name=\"region\" id=\"region\">\n");
      out.write("\t\t\t\t\t\t\t<!-- 나중에 THEME 테이블에서 테마 이름, 테마 그림을 가져와야한다.  -->\n");
      out.write("\t\t      \t\t\t\t\t<option data-class=\"podcast\">강남</option>\n");
      out.write("\t\t    \t\t\t  \t\t\n");
      out.write("\t\t     \t\t\t\t\t<option data-class=\"podcast\" selected=\"selected\">회기</option>\n");
      out.write("\t\t      \t\t\t\t\t<option data-class=\"podcast\">이태원</option>\n");
      out.write("\t\t      \t\t\t\t\t<option data-class=\"podcast\">놀이동산</option>\n");
      out.write("\t   \t\t\t\t\t\t </select>\n");
      out.write("   \t\t\t\t\t\t </td>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" ></td>\n");
      out.write("\t\t\t\t\t\t<td  style=\"visibility:hidden;\">empty</td>\n");
      out.write("\t\t\t\t\t</tr>\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" class=\"color \"> 예상 소요 시간</td>\n");
      out.write("\t\t\t\t\t\t<td width=\"40\" align=\"left\"><input type=\"text\" name= \"subject\" size=\"40\"></td>\n");
      out.write("\t\t\t\t\t</tr>\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" ></td>\n");
      out.write("\t\t\t\t\t\t<td  style=\"visibility:hidden;\">empty</td>\n");
      out.write("\t\t\t\t\t</tr>\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" ></td>\n");
      out.write("\t\t\t\t\t\t<td  style=\"visibility:hidden;\">empty</td>\n");
      out.write("\t\t\t\t\t</tr>\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<td ><div id='View_area' style='position:relative; width: 100px; height: 100px; color: black; border: 0px solid black; dispaly: inline; '></div></td>\n");
      out.write("\t\t\t\t\t<td width=\"5%\" align=\"center\" ><input type=\"file\" name=\"profile_pt\" id=\"profile_pt\" onchange=\"previewImage(this,'View_area')\"></td>\n");
      out.write("\t\t\t\t\t</tr>\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<!-- <input type=\"file\" name=\"profile_pt\" id=\"profile_pt\" onchange=\"previewImage(this,'View_area')\">\n");
      out.write("<div id='View_area' style='position:relative; width: 100px; height: 100px; color: black; border: 0px solid black; dispaly: inline; '></div> -->\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\">\n");
      out.write("\t\t\t\t\t\t<textarea rows=\"10\" cols=\"60\" name= \"content\" id=\"content\">\n");
      out.write("\t\t\t\t\t\tthis is my textarea to be replace with ckeditor.\n");
      out.write("\t\t\t\t\t\t</textarea>\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t\tvar editor = CKEDITOR.replace('content',{\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t\t</script>\n");
      out.write("\t\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" ></td>\n");
      out.write("\t\t\t\t\t\t<td  style=\"visibility:hidden;\">empty</td>\n");
      out.write("\t\t\t\t\t</tr>\t\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<td width=\"5%\" align=\"center\" ></td>\n");
      out.write("\t\t\t\t\t\t<td  style=\"visibility:hidden;\">empty</td>\n");
      out.write("\t\t\t\t\t</tr>\t\n");
      out.write("\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t<p align=\"right\">\n");
      out.write("\t\t\t\t\t<input class=\"btn color click\" type=\"button\" value=\"작성 하기\"  onclick=\"check()\" />\n");
      out.write("\t\t\t\t\t<input class=\"btn color click\" type=\"button\" value=\"작성 취소\"/> \n");
      out.write("\t\t\t\t\t</p>\n");
      out.write(" \t\n");
      out.write(" \t\n");
      out.write(" \t</form>\n");
      out.write(" \t</div>\n");
      out.write(" \t\n");
      out.write(" \t<!-- footer -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
